Bump golang.org/x/net from v0.54.0 to v0.55.0
Fixes ci-kubernetes-e2e-kind-golang-tip and ci-kubernetes-unit-golang-tip,
which started failing under Go tip identifying as go1.27 with:

  vendor/google.golang.org/grpc/internal/transport/handler_server.go:271:18:
      undefined: http2.TrailerPrefix

In x/net v0.54.0, TrailerPrefix was defined only in http2/server.go, which
carries `//go:build !(go1.27 && !http2legacy)` and is therefore excluded
under go1.27. Upstream golang/net commit 1efab4271a moved TrailerPrefix
(and other symbols accidentally dropped by the go1.27 server wrapper) into
common files. That fix is released in v0.55.0.

Tracked in https://github.com/kubernetes/kubernetes/issues/139257

Kubernetes-commit: d7c6b52ac4b6387d740af2fea7f1dd007d71c64c